  steps:
  #Maven version
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ['--version']
  
  #Maven test
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ['test']
  
  # Maven packate
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ['package','-Dmaven.test.skip=true']
  
  - name: gcr.io/cloud-builders/docker
    args:
      ["build", "-t", "gcr.io/chromatic-hue-367100/demo:$COMMIT_SHA", "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/chromatic-hue-367100/demo"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "demo",
        "--image",
        "gcr.io/chromatic-hue-367100/demo:$COMMIT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]   
    